package com.interconn.entity;

public enum AuditAction {
    LOGIN,
    SUPERVISOR_ACTIVATED,
    INSPECTION_CREATED,
    EVIDENCE_UPLOADED,
    OCR_PROCESSED,
    AI_EXTRACTED,
    PRODUCT_MODIFIED,
    PRODUCT_VERIFIED,
    COMPLIANCE_VALIDATED,
    REPORT_GENERATED
}
